### ISSUE TITLE
Ios Background Bluetooth Scanning

### ISSUE THREAD

**Issue by sridharmari** [mash/BLE-Proximity#1]
Hi mash,

Thanks for your code man, We have used open trace code for our contact tracing. Though the app is working fine in foreground, when the app  goes to background I was not able to get the values. 

Regards,

sridhar

**Comment by mash** [comment]
Well, yes. Not only opentrace, but iOS in general, an iOS app in background almost cannot find an iOS app advertising in background.
Once the peripheral is found, I implemented a trick to keep the connection, as seen in https://github.com/mash/BLE-Proximity/blob/master/BProximity/BProximity/CentralManager.swift#L26
but the first didDiscover is rarely called when both the peripheral and central is in background.

That's the current situation of iOS, without using ExposureNotification framework.
